baseURL = "dfir.fi"
title   = "DFIR ≫ List of service providers in Finland"
languageCode = "en-us"
theme = "provider-list"

[params]
  [[params.navigation]]
    text = "Contribute"
    link = "https://github.com/dfir-fi/dfir-fi"
    external = true
  [[params.navigation]]
    text = "Author"
    link = "https://blog.dfir.fi/about/"
    external = true
  [[params.navigation]]
    text = "SOC providers"
    link = "https://csoc.fi"
    external = true

  [params.index]
    page_title = "List of DFIR service providers"
    description = """
    This is a list of Digital Forensics & Incident Response (DFIR) companies in Finland. These companies can help you in case of a security incident. Purpose of this list is to give organizations a list of active DFIR companies.
    <br><br>
    Please note that this is a list of companies, who provide DFIR support with one-off contracts (e.q. the customer does not have to have continuous agreement with the company to get help).
    """

  [params.ad]
    ad1 = { title = "Tietoturva­poikkeamien selvitys (DFIR)", description = "Koulutus tietoturvapoikkeamien selvitykseen ja tutkintaan. Kouluttajana Juho Jauhiainen.", button_text = "Lue lisää", button_link = "https://example.com" }
    ad2 = { title = "Suomalainen DFIR-yhteisö", description = "Kiinnostaako suomalainen Discord-yhteiso DFIR-asiantuntijoille? Ryhmä on luotu tiedonvaihtoa varten. Liittymään pääset ratkaisemalla haasteen.", button_text = "Liity mukaan", button_link = "https://example.com" }
