name = "Provider List"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.114.0"

[author]
  name = "Juho Jauhiainen"
  homepage = "https://whois.dfir.fi"

